name: Déploiement sur Google Cloud

on:
  push:
    branches:
      - main  # Déclenche l'action sur les pushes vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
